export const IPC_CHANNELS = {
  ACTIONS: {
    MINIMIZE: 'actions:minimize',
    RESTORE: 'actions:restore',
    CLOSE: 'actions:close',
  },
  STEAM: {
    IS_ONLINE: 'steam:isOnline',
  },
  WORKSHOP: {
    GET_ALL_ITEMS: 'workshop:getAllItems',
    GET_MY_PUBLISHED_ITEMS: 'workshop:getMyPublishedItems',
    SUBSCRIBE: 'workshop:subscribe',
    UNSUBSCRIBE: 'workshop:unsubscribe',
    GET_SUBSCRIBED_ITEMS: 'workshop:getSubscribedItems',
    DOWNLOAD_ITEM: 'workshop:downloadItem',
    DOWNLOAD_INFO: 'workshop:downloadInfo',
    GET_INSTALL_INFO: 'workshop:getInstallInfo',
    OPEN_IN_STEAM_CLIENT: 'workshop:openInSteamClient',
    CREATE: 'workshop:create',
    UPDATE_ITEM: 'workshop:updateItem',
    GET_MY_ITEMS: 'workshop:getMyItems',
    OPEN_IN_STEAM_CLIENT_UPLOADED_FILES: 'workshop:openInSteamClientUploadedFiles',
  },
  LAYOUTS: {
    GET_LAYOUTS: 'layouts:getLayouts',
    GET_LAYOUTS_ORDER: 'layouts:getLayoutsOrder',
    CREATE_LAYOUT: 'layouts:createLayout',
    DELETE_LAYOUT: 'layouts:deleteLayout',
    UPDATE_LAYOUT: 'layouts:updateLayout',
    REORDER_LAYOUTS: 'layouts:reorderLayouts',
    GET_ACTIVE_LAYOUT: 'layouts:getActiveLayout',
    SET_ACTIVE_LAYOUT: 'layouts:setActiveLayout',
  },
  OVERLAY: {
    OPEN: 'overlay:open',
    CLOSE: 'overlay:close',
    UPDATE_EDIT_MODE: 'overlay:updateEditMode',
    UPDATE_SETTINGS: 'overlay:updateSettings',
    SERVE_PREVIEW: 'overlay:serverPreview',
    STOP_SERVING_PREVIEW: 'overlay:stopServingPreview',
    GENERATE_THUMBNAIL: 'overlay:generateThumbnail',
  },
  FS: {
    READ: 'fs:read',
  },
} as const;
