import {
  Settings,
  Monitor,
  Palette,
  Sliders,
  Eye,
  Layout,
  Type,
  Zap,
  Users,
  Trophy,
  Clock,
  BarChart3,
  Target,
  Gamepad2,
  Radio,
  Database,
  Shield,
  Wrench,
  Layers,
  Grid,
  MousePointer,
  Smartphone,
  Tablet,
  Laptop,
  Volume2,
  Bell,
  Star,
  Heart,
  Flag,
  Map,
  Navigation,
  Compass,
  Activity,
  TrendingUp,
  PieChart,
  BarChart,
  LineChart,
  Calendar,
  Filter,
  Search,
  Tag,
  Bookmark,
  Share,
  Download,
  Upload,
  Save,
  Edit,
  Copy,
  Trash,
  X,
  Check,
  AlertTriangle,
  Info,
  HelpCircle,
  Lock,
  Unlock,
  Key,
  User,
  Mail,
  Phone,
  MessageSquare,
  Send,
  Inbox,
  Archive,
  Folder,
  File,
  FileText,
  Image as ImageIcon,
  Video,
  Music,
  Headphones,
  Camera,
  Mic,
  Play,
  Pause,
  Store as Stop,
  Copyright as Brightness,
  Sun,
  Moon,
  CloudRain,
  Cloud,
  Thermometer,
  Wind,
  Droplets,
  Snowflake,
  Flame,
  Zap as Lightning,
  Cpu,
  HardDrive,
  Wifi as WifiIcon,
  Bluetooth,
  Battery,
  Power,
  Plug,
  Cable,
  Router,
  Server,
  Globe,
  Link,
  Home,
  Building,
  Car,
  Plane,
  Train,
  Bike,
  MapPin,
  Route,
  Timer,
  Watch as Stopwatch,
  AlarmClock,
  Watch,
  Hourglass,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Maximize,
  Minimize,
  Move,
  Maximize as Resize,
  ZoomIn,
  ZoomOut,
  Focus,
  Crosshair,
  Aperture,
  Contrast,
  Crop,
  Scissors,
  PaintBucket,
  Brush,
  Pen,
  Pencil,
  Eraser,
  Ruler,
  Triangle,
  Square,
  Circle,
  Hexagon,
  Diamond,
  Shapes,
  Box,
  Package,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Euro,
  PoundSterling,
  Pen as Yen,
  Bitcoin,
  Coins,
  Wallet,
  Receipt,
  Calculator,
  Award,
  Medal,
  Crown,
  Gem,
  Sparkles,
  Wand,
  Magnet as Magic,
  Rocket,
  Satellite,
  Radar,
  Telescope,
  Microscope,
  Atom,
  Dna,
  Beaker,
  Pill,
  Syringe,
  Stethoscope,
  Ban as Bandage,
  Cross,
  Plus as PlusIcon,
  Minus as MinusIcon,
  Equal,
  Percent,
  Hash,
  AtSign,
  Asterisk,
  Slash,
  Pipette as Pipe,
} from 'lucide-react';
import React from 'react';

import { OverlayManifestIconType } from '@/main/shared/schemas/overlay-manifest-file-schema';

export const iconMap: Record<OverlayManifestIconType, React.ComponentType<any>> = {
  // General/Settings
  settings: Settings,
  sliders: Sliders,
  wrench: Wrench,
  gear: Settings,

  // Display/Visual
  monitor: Monitor,
  eye: Eye,
  layout: Layout,
  palette: Palette,
  type: Type,
  image: ImageIcon,
  layers: Layers,
  grid: Grid,
  brightness: Brightness,
  contrast: Contrast,
  sun: Sun,
  moon: Moon,

  // Performance/System
  zap: Zap,
  lightning: Lightning,
  cpu: Cpu,
  'hard-drive': HardDrive,
  activity: Activity,
  'trending-up': TrendingUp,
  'bar-chart': BarChart,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  'bar-chart-3': BarChart3,

  // Gaming/Racing
  gamepad: Gamepad2,
  trophy: Trophy,
  target: Target,
  flag: Flag,
  users: Users,
  user: User,
  crown: Crown,
  award: Award,
  medal: Medal,
  car: Car,
  timer: Timer,
  stopwatch: Stopwatch,
  clock: Clock,

  // Content/Media
  'file-text': FileText,
  file: File,
  folder: Folder,
  video: Video,
  music: Music,
  headphones: Headphones,
  camera: Camera,
  mic: Mic,
  volume: Volume2,
  play: Play,
  pause: Pause,
  stop: Stop,

  // Navigation/UI
  'mouse-pointer': MousePointer,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  home: Home,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  'map-pin': MapPin,
  route: Route,

  // Network/Connection
  wifi: WifiIcon,
  radio: Radio,
  bluetooth: Bluetooth,
  globe: Globe,
  link: Link,
  server: Server,
  database: Database,
  router: Router,

  // Actions/Tools
  edit: Edit,
  copy: Copy,
  save: Save,
  download: Download,
  upload: Upload,
  share: Share,
  search: Search,
  filter: Filter,
  tag: Tag,
  bookmark: Bookmark,
  plus: PlusIcon,
  minus: MinusIcon,
  x: X,
  check: Check,
  trash: Trash,

  // Status/Alerts
  bell: Bell,
  'alert-triangle': AlertTriangle,
  info: Info,
  'help-circle': HelpCircle,
  star: Star,
  heart: Heart,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  key: Key,

  // Shapes/Design
  circle: Circle,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,
  diamond: Diamond,
  shapes: Shapes,
  box: Box,
  package: Package,

  // Science/Tech
  atom: Atom,
  dna: Dna,
  beaker: Beaker,
  telescope: Telescope,
  microscope: Microscope,
  rocket: Rocket,
  satellite: Satellite,
  radar: Radar,

  // Weather/Nature
  cloud: Cloud,
  'cloud-rain': CloudRain,
  wind: Wind,
  droplets: Droplets,
  snowflake: Snowflake,
  flame: Flame,
  thermometer: Thermometer,

  // Business/Finance
  'dollar-sign': DollarSign,
  euro: Euro,
  'pound-sterling': PoundSterling,
  yen: Yen,
  bitcoin: Bitcoin,
  coins: Coins,
  wallet: Wallet,
  'credit-card': CreditCard,
  'shopping-cart': ShoppingCart,
  receipt: Receipt,
  calculator: Calculator,

  // Magic/Special
  sparkles: Sparkles,
  wand: Wand,
  gem: Gem,
  magic: Magic,

  // Time/Calendar
  calendar: Calendar,
  'alarm-clock': AlarmClock,
  watch: Watch,
  hourglass: Hourglass,

  // Movement/Transform
  move: Move,
  resize: Resize,
  'rotate-cw': RotateCw,
  'rotate-ccw': RotateCcw,
  'refresh-cw': RefreshCw,
  maximize: Maximize,
  minimize: Minimize,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  focus: Focus,
  crosshair: Crosshair,

  // Art/Design Tools
  'paint-bucket': PaintBucket,
  brush: Brush,
  pen: Pen,
  pencil: Pencil,
  eraser: Eraser,
  ruler: Ruler,
  crop: Crop,
  scissors: Scissors,
  aperture: Aperture,

  // Power/Energy
  battery: Battery,
  power: Power,
  plug: Plug,
  cable: Cable,

  // Communication
  mail: Mail,
  phone: Phone,
  'message-square': MessageSquare,
  send: Send,
  inbox: Inbox,
  archive: Archive,

  // Transportation
  plane: Plane,
  train: Train,
  bike: Bike,
  building: Building,

  // Medical/Health
  cross: Cross,
  pill: Pill,
  syringe: Syringe,
  stethoscope: Stethoscope,
  bandage: Bandage,

  // Symbols/Math
  equal: Equal,
  percent: Percent,
  hash: Hash,
  'at-sign': AtSign,
  asterisk: Asterisk,
  slash: Slash,
  pipe: Pipe,
};
