import { mainLogger as logger } from "./loggers";
process.on("uncaughtException", (error) => {
  console.error("Uncaught Exception:", error);
  logger.error("Uncaught Exception:", error.message);
  process.exit(1);
});

import { app, globalShortcut } from "electron";
import { createMainWindow } from "./services/window-manager-service/main-window-manager";
import { startServers } from "./services/server-manager";
// import { registerShortcuts } from "./services/ui/shortcutManager";
import { OverlayWindowManager } from "./services/window-manager-service/overlay-window-manager";
import gameDataHandler from "./services/game-data";
import { initSteamClient } from "./utils/steam-client";
import { STEAM_WORKSHOP_CONTENT_PATH } from "./main-constants";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const client = initSteamClient();
if (client) {
  const { accountId, steamId32, steamId64 } = client.localplayer.getSteamId();
  logger.info(
    `${client.localplayer.getName()} [${accountId}][${steamId32}][${steamId64}] has opened the app`,
  );
  logger.info(`Build ID: ${client.apps.appBuildId()}`);
  // if (!client.apps.isAppInstalled(STEAM_APP_ID)) {
  //   logger.warn("App is not installed in Steam Client. Exitting...");
  //   process.exit(0);
  // }
}
logger.info(`Steam Workshop content path: ${STEAM_WORKSHOP_CONTENT_PATH}`);

export const overlayWindowManager = new OverlayWindowManager();

gameDataHandler.addListener("isConnected", (c) => {
  if (!c) {
    overlayWindowManager.closeAllOverlays();
  } else {
    overlayWindowManager.updateOverlayWindows();
  }
});

app.on("ready", () => {
  createMainWindow(
    MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    MAIN_WINDOW_WEBPACK_ENTRY,
  );
  // registerShortcuts();
  startServers();
  overlayWindowManager.updateOverlayWindows();
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  createMainWindow(
    MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    MAIN_WINDOW_WEBPACK_ENTRY,
  );
});

app.on("will-quit", () => {
  globalShortcut.unregisterAll();
});
