import { app, globalShortcut } from "electron";
import { createMainWindow } from "./services/window-manager-service/main-window-manager";
import { startServers } from "./services/server-manager";
// import { registerShortcuts } from "./services/ui/shortcutManager";
import { OverlayWindowManager } from "./services/window-manager-service/overlay-window-manager";
import gameDataHandler from "./services/game-data";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const overlayWindowManager = new OverlayWindowManager();

gameDataHandler.addListener("isConnected", (c) => {
  if (!c) {
    overlayWindowManager.closeAllOverlays();
  } else {
    overlayWindowManager.updateOverlayWindows();
  }
});
app.on("ready", () => {
  createMainWindow(
    MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    MAIN_WINDOW_WEBPACK_ENTRY,
  );
  // registerShortcuts();
  startServers();
  overlayWindowManager.updateOverlayWindows();
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  createMainWindow(
    MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    MAIN_WINDOW_WEBPACK_ENTRY,
  );
});

app.on("will-quit", () => {
  globalShortcut.unregisterAll();
});
